using Newtonsoft.Json;
using Stripe;

namespace StripeGateway
{
    public class StripeSetuptIntentResponse
    {
        public string Id { get; set; }
        public Application Application { get; set; }

        public SetupIntentAutomaticPaymentMethods AutomaticPaymentMethods { get; set; }
        public bool AttachToSelf { get; set; }
        public string CancellationReason { get; set; }
        public string ClientSecret { get; set; }
        public DateTime Created { get; set; }
        public string Description { get; set; }
        public List<string> FlowDirections { get; set; }
        public StripeError LastSetupError { get; set; }


        #region Expandable Customer

        /// <summary>
        /// (ID of the Customer)
        /// ID of the Customer this SetupIntent belongs to, if one exists.
        ///
        /// If present, the SetupIntent's payment method will be attached to the Customer on
        /// successful setup. Payment methods attached to other Customers cannot be used with this
        /// SetupIntent.
        /// </summary>
        [JsonIgnore]
        public string CustomerId { get; set; }

        /// <summary>
        /// (Expanded)
        /// ID of the Customer this SetupIntent belongs to, if one exists.
        ///
        /// If present, the SetupIntent's payment method will be attached to the Customer on
        /// successful setup. Payment methods attached to other Customers cannot be used with this
        /// SetupIntent.
        ///
        /// For more information, see the <a href="https://stripe.com/docs/expand">expand documentation</a>.
        /// </summary>
        [JsonIgnore]
        public Customer Customer { get; set; }

        #endregion


        #region Expandable LatestAttempt

        /// <summary>
        /// (ID of the SetupAttempt)
        /// The most recent SetupAttempt for this SetupIntent.
        /// </summary>
        [JsonIgnore]
        public string LatestAttemptId { get; set; }

        /// <summary>
        /// (Expanded)
        /// The most recent SetupAttempt for this SetupIntent.
        ///
        /// For more information, see the <a href="https://stripe.com/docs/expand">expand documentation</a>.
        /// </summary>
        [JsonIgnore]
        public SetupAttempt LatestAttempt { get; set; }
        #endregion


        public bool Livemode { get; set; }

        #region Expandable Mandate

        /// <summary>
        /// (ID of the Mandate)
        /// ID of the multi use Mandate generated by the SetupIntent.
        /// </summary>
        [JsonIgnore]
        public string MandateId { get; set; }

        /// <summary>
        /// (Expanded)
        /// ID of the multi use Mandate generated by the SetupIntent.
        ///
        /// For more information, see the <a href="https://stripe.com/docs/expand">expand documentation</a>.
        /// </summary>
        [JsonIgnore]
        public Mandate Mandate { get; set; }
        #endregion

        /// <summary>
        /// Set of <a href="https://stripe.com/docs/api/metadata">key-value pairs</a> that you can
        /// attach to an object. This can be useful for storing additional information about the
        /// object in a structured format.
        /// </summary>
        [JsonProperty("metadata")]
        public Dictionary<string, string> Metadata { get; set; }

        /// <summary>
        /// If present, this property tells you what actions you need to take in order for your
        /// customer to continue payment setup.
        /// </summary>
        [JsonProperty("next_action")]
        public SetupIntentNextAction NextAction { get; set; }

        #region Expandable OnBehalfOf

        /// <summary>
        /// (ID of the Account)
        /// The account (if any) for which the setup is intended.
        /// </summary>
        [JsonIgnore]
        public string OnBehalfOfId { get; set; }

        /// <summary>
        /// (Expanded)
        /// The account (if any) for which the setup is intended.
        ///
        /// For more information, see the <a href="https://stripe.com/docs/expand">expand documentation</a>.
        /// </summary>
        [JsonIgnore]
        public Account OnBehalfOf { get; set; }
        #endregion

        #region Expandable PaymentMethod

        /// <summary>
        /// (ID of the PaymentMethod)
        /// ID of the payment method used with this SetupIntent. If the payment method is
        /// <c>card_present</c> and isn't a digital wallet, then the <a
        /// href="https://docs.stripe.com/api/setup_attempts/object#setup_attempt_object-payment_method_details-card_present-generated_card">generated_card</a>
        /// associated with the <c>latest_attempt</c> is attached to the Customer instead.
        /// </summary>
        [JsonIgnore]
        public string PaymentMethodId { get; set; }

        /// <summary>
        /// (Expanded)
        /// ID of the payment method used with this SetupIntent. If the payment method is
        /// <c>card_present</c> and isn't a digital wallet, then the <a
        /// href="https://docs.stripe.com/api/setup_attempts/object#setup_attempt_object-payment_method_details-card_present-generated_card">generated_card</a>
        /// associated with the <c>latest_attempt</c> is attached to the Customer instead.
        ///
        /// For more information, see the <a href="https://stripe.com/docs/expand">expand documentation</a>.
        /// </summary>
        [JsonIgnore]
        public PaymentMethod PaymentMethod { get; set; }
        #endregion

        /// <summary>
        /// Information about the <a
        /// href="https://stripe.com/docs/api/payment_method_configurations">payment method
        /// configuration</a> used for this Setup Intent.
        /// </summary>
        [JsonProperty("payment_method_configuration_details")]
        public SetupIntentPaymentMethodConfigurationDetails PaymentMethodConfigurationDetails { get; set; }

        /// <summary>
        /// Payment method-specific configuration for this SetupIntent.
        /// </summary>
        [JsonProperty("payment_method_options")]
        public SetupIntentPaymentMethodOptionsResponse PaymentMethodOptions { get; set; }

        /// <summary>
        /// The list of payment method types (e.g. card) that this SetupIntent is allowed to set up.
        /// </summary>
        [JsonProperty("payment_method_types")]
        public List<string> PaymentMethodTypes { get; set; }

        #region Expandable SingleUseMandate

        /// <summary>
        /// (ID of the Mandate)
        /// ID of the single_use Mandate generated by the SetupIntent.
        /// </summary>
        [JsonIgnore]
        public string SingleUseMandateId { get; set; }
        /// <summary>
        /// (Expanded)
        /// ID of the single_use Mandate generated by the SetupIntent.
        ///
        /// For more information, see the <a href="https://stripe.com/docs/expand">expand documentation</a>.
        /// </summary>
        [JsonIgnore]
        public Mandate SingleUseMandate { get; set; }
        #endregion

        /// <summary>
        /// <a href="https://stripe.com/docs/payments/intents#intent-statuses">Status</a> of this
        /// SetupIntent, one of <c>requires_payment_method</c>, <c>requires_confirmation</c>,
        /// <c>requires_action</c>, <c>processing</c>, <c>canceled</c>, or <c>succeeded</c>.
        /// One of: <c>canceled</c>, <c>processing</c>, <c>requires_action</c>,
        /// <c>requires_confirmation</c>, <c>requires_payment_method</c>, or <c>succeeded</c>.
        /// </summary>
        [JsonProperty("status")]
        public string Status { get; set; }

        /// <summary>
        /// Indicates how the payment method is intended to be used in the future.
        ///
        /// Use <c>on_session</c> if you intend to only reuse the payment method when the customer
        /// is in your checkout flow. Use <c>off_session</c> if your customer may or may not be in
        /// your checkout flow. If not provided, this value defaults to <c>off_session</c>.
        /// </summary>
        [JsonProperty("usage")]
        public string Usage { get; set; }

    }
}
